name: 'coverage'
on:
    pull_request_target:
        types: [assigned, opened, synchronize, reopened]
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: Hello world!
